from enum import Enum
from pydantic import BaseModel, Field


class ApprovalStatus(str, Enum):
    """Permission gate status states."""
    AUTO_APPROVED = "auto_approved"
    REQUIRES_MERCHANT_APPROVAL = "requires_merchant_approval"
    BLOCKED_BY_POLICY = "blocked_by_policy"


# --- LLM Ingestion & Structured Output Schemas ---

class LLMReasoningInput(BaseModel):
    """Input payload for LLM executive strategy reasoning."""
    merchant_id: str
    top_opportunity_title: str
    total_opportunity_gmv: float
    total_customers: int
    dormant_vip_count: int
    payment_success_rate: float


class LLMReasoningOutput(BaseModel):
    """Structured executive reasoning generated by LLM."""
    executive_summary: str
    revenue_leak_root_cause: str
    projected_roi_analysis: str
    recommended_immediate_action: str
    reasoning_trace: str | None = None
    provider_used: str | None = None


class LLMCopyGenerationInput(BaseModel):
    """Input payload for generating individual marketing message copy."""
    customer_name: str
    favorite_category: str
    offer_description: str
    urgency_text: str = "Limited time offer"
    tone: str = "enthusiastic and warm"


class LLMCopyGenerationOutput(BaseModel):
    """Structured multi-channel copy generated by LLM."""
    subject: str
    email_body: str
    whatsapp_body: str
    channel: str = "email"


class LLMChatInput(BaseModel):
    """Input payload for merchant conversational questions."""
    merchant_id: str
    session_id: str | None = None
    query: str
    total_customers: int = 0
    total_revenue: float = 0.0
    dormant_vip_count: int = 0
    trace_context: dict | None = None


class LLMChatOutput(BaseModel):
    """Structured reply generated by the growth chat agent."""
    reply: str
    suggested_follow_up_action: str | None = None
    reasoning_trace: str | None = None
    provider_used: str | None = None
    tools_used: list[str] = Field(default_factory=list)
    tool_data: dict = Field(default_factory=dict)


# --- Agent Layer Schemas with Explicit Reasoning ---

class CustomerTargetProfile(BaseModel):
    """Structured representation of an individual targeted customer."""
    customer_id: str
    name: str
    email: str
    favorite_category: str
    segment: str
    total_spend: float


class AudienceSelectionOutput(BaseModel):
    """Structured output from CustomerAgent detailing targeted audience cohort."""
    opportunity_id: str
    target_segment: str
    total_audience_count: int
    target_customers: list[CustomerTargetProfile] = Field(default_factory=list)
    reasoning: str = ""


class OfferRecommendationOutput(BaseModel):
    """Structured output from OfferAgent defining incentive terms."""
    offer_code: str
    discount_type: str
    discount_value: float
    min_order_value: float
    description: str
    urgency_text: str
    reasoning: str = ""


class CampaignCopyOutput(BaseModel):
    """Structured output from CampaignAgent with individualized messaging copy."""
    channel: str = "email"
    subject: str
    email_body: str
    whatsapp_body: str | None = None
    template_type: str
    reasoning: str = ""


class PermissionGateResult(BaseModel):
    """Structured evaluation of guardrail safety policies before executing an action."""
    status: ApprovalStatus
    is_executable: bool
    policy_notes: str
    max_allowed_discount_percentage: float = 20.0
    estimated_cost_inr: float = 0.0
    reasoning: str = ""


class ExperimentMetricsOutput(BaseModel):
    """Structured output from ExperimentAgent measuring conversion lift and normalized incremental financial ROI."""
    treatment_conversion_rate: float
    control_conversion_rate: float
    conversion_lift_percentage: float | None = None
    relative_lift_display: str = "N/A"
    absolute_difference_percentage: float = 0.0
    treatment_total_count: int = 0
    control_total_count: int = 0
    treatment_orders_count: int = 0
    control_orders_count: int = 0
    incremental_orders_count: int
    incremental_revenue_inr: float
    status_note: str = ""
    reasoning: str = ""



class GrowthPlanOutput(BaseModel):
    """Consolidated master plan produced by GrowthManagerAgent."""
    merchant_id: str
    opportunity_id: str
    opportunity_title: str
    estimated_gmv_impact: float
    confidence_score: float
    audience: AudienceSelectionOutput
    offer: OfferRecommendationOutput
    campaign_copy: CampaignCopyOutput
    permission_gate: PermissionGateResult
    ai_reasoning: str
    reasoning_trace: str | None = None
    provider_used: str | None = None


# --- Agentic Tool-Calling Schemas ---

class ToolCall(BaseModel):
    """Structured tool execution request from LLM."""
    id: str = "call_0"
    name: str
    arguments: dict = Field(default_factory=dict)


class LLMToolResponse(BaseModel):
    """Standardized response from tool-calling LLM invocation."""
    stop_reason: str  # "tool_use" | "final_answer"
    tool_call: ToolCall | None = None
    content: str | None = None
    reasoning_trace: str | None = None
    provider_used: str | None = None


class AgenticStepRecord(BaseModel):
    """Execution record for a single tool iteration in the agentic loop."""
    step_number: int
    tool_name: str
    arguments: dict = Field(default_factory=dict)
    result: dict = Field(default_factory=dict)
    step_summary: str = ""


class AgenticScanResult(BaseModel):
    """Consolidated output from bounded agentic decision scan."""
    merchant_id: str
    plan_summary: str
    steps_taken: list[AgenticStepRecord] = Field(default_factory=list)
    memory_citations: list[dict] = Field(default_factory=list)
    reasoning_trace: str | None = None
    provider_used: str | None = None
    status: str = "completed"


class StepEvent(BaseModel):
    """Event emitted during live streaming of multi-agent growth scans."""
    step: str
    status: str = "completed"
    data: dict | list | str | int | float | None = None
    step_number: int | None = None
    summary: str | None = None


